name: "SSH Setup"
author: "MrSquaare"
description: "Setup SSH"
branding:
  icon: terminal
  color: gray-dark
inputs:
  host:
    description: "SSH host"
    required: true
  port:
    description: "SSH port"
    default: "22"
    required: false
  private-key:
    description: "SSH private key"
    required: true
  private-key-name:
    description: "SSH private key name"
    default: "id_rsa"
    required: false
outputs:
  ssh-path:
    description: "Path to the SSH private key"
  ssh-agent-pid:
    description: "PID of the SSH agent"
  ssh-auth-sock:
    description: "Path to the SSH auth socket"
runs:
  using: "node20"
  main: "lib/index.js"
  post: "lib/cleanup.js"
  post-if: "always()"
