name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Check lint and format
        run: |
          pnpm check

  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: |
          pnpm build
